### ISSUE TITLE
Could not find gem 'omniauth-zoom' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by kittrCZ** [nikhgupta/omniauth-zoom#1]
Hi, I was trying to install this gem and got following message:

```
Could not find gem 'omniauth-zoom' in any of the gem sources listed in your Gemfile.
```

The gem is not published to https://rubygems.org/. Why?

**Comment by LucasCioffi** [comment]
Hi @kittrCZ here's another option for your gemfile:
`gem 'omniauth-zoom', github: 'nikhgupta/omniauth-zoom'`

**Comment by kittrCZ** [comment]
Thanks, works like a charm
